[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe_stripped = { workspace = true }
eframe_rebuilt = { workspace = true }
egui = { workspace = true }
env_logger = { workspace = true }
winit = { workspace = true }
